### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by francoisnicolas** [VirtCode/SmartMouse#17]
Would it be possible to have the sources with an MIT or Apache 2.0 license ?

**Comment by VirtCode** [comment]
I currently don't have any plans to license it under MIT, Apache, or any other permissive license.
I have deliberately chosen the GPL as I have invested a significant amount of time into the position estimation sensor fusion and want to see it continued in the open and not just being profited off of.

May I ask what you would use the code for if it were under a more permissive license?

**Comment by VirtCode** [comment]
Okay I see. For the implementation of the Bluetooth HID profile under Android, you'll probably also find what you need in this sample implementation which I also used as a reference: [ginkage/wearmouse](https://github.com/ginkage/wearmouse) (and which is licensed under Apache)
