### ISSUE TITLE
app interferes with home app / launcher selection

### ISSUE THREAD

**Issue by Lanchon** [VirtCode/SmartMouse#19]
hi,

thanks for the app!

in android, if there is more than one launcher app installed, hitting the home button will cause the system to ask which app will handle the "home" intent. in that situation, you can select a launcher and hit "always" and have the system store your preference and not ask again (while the home intent receiver list stays the same).

in at least lineageos 20, at least in some versions, the presence of this app causes the system to misbehave. when this app is installed along side more than one launcher app, then the home app selection menu will pop up every time the home button in hit, even if you select "always", even if you configure the home app in settings.

for whatever reason, this app makes the system ignore the home app preference and ask every time. this bug makes the app unusable if you use a 3rd party launcher. (btw, i suppose the bug is in android, but i image it can be worked around in the app.)

# steps to repro:

- uninstall or freeze this app.
- install 3rd party launcher like neo launcher.
- hit home and select a preferred launcher.
- hit home again and check the selection sticks.
- install or unfreeze this app.
- hit home and check that home selection is no longer memorized.

# notes

- i am running a self-compiled lineageos 20 with microg. but i have reason to believe this happens at least in lineageos versions 16 through 20 and is independent of device. i am reporting this in the belief/hope that it will be trivial to reproduce. if it is not, tell me and i can investigate further.
- this happened in the past already, even to google. if you google around, you will find that an update to google's "digital wellbeing" app started causing this same issue, but only at a certain time of day. it was acknowledged and fixed by google a couple of months later. given that this happened 2 years ago, and i am experiencing a similar issue now, it looks like google could not be bothered to fix the underlying issue in android that apparently any app can trigger at any time, not even in a major OS update.

please tell me if you are able to repro.

thanks again!

**Comment by VirtCode** [comment]
Thanks a lot for such a detailed bug report!

It looks like this is the same problem as #15, which was fixed on main.
Could you try building from main (or downloading and trying the prebuilt apk from the other issue), and see whether that also fixes the issue on your end?

**Comment by Lanchon** [comment]
thanks!

very sorry for not having found that :(
yes, master fixes the issue for me too.

on the other hand, i can't connect to my pc. probably for the best, as i would have ended contributing to the motion estimation and i really don't have time for that, lol.

thank you!
