### ISSUE TITLE
versioning

### ISSUE THREAD

**Issue by IzzySoft** [VirtCode/SmartMouse#5]
I've just noticed the APK attached to release v1.4.0 identifies as

    package: name='ch.virt.smartphonemouse' versionCode='1' versionName='1.0'

Could you please take care for proper [versioning](https://github.com/VirtCode/SmartMouse/blob/main/app/build.gradle#L13), i.e. increasing `versionCode` with each release and adjust `versionName` properly? Thanks in advance!

For background: the former is used by Android internally to keep versions apart and to decide whether an APK provides an update – the latter is for humans to read.

**Comment by VirtCode** [comment]
Thanks for pointing that out!
I've updated these numbers to something suitable and updated the built APK under the [1.4.0](https://github.com/VirtCode/SmartMouse/releases/tag/v1.4.0) release.

**Comment by IzzySoft** [comment]
Thanks! That looks much better now :wink: Just noticed the APK is signed by a debug key. Don't you want to create your own dedicated "release key"? You can still enable the debug flag with that.

Apart from that, with the next sync around 7 pm UTC your app will become [available here](https://apt.izzysoft.de/packages/ch.virt.smartphonemouse/) in my repo, and look like this:

![image](https://github.com/VirtCode/SmartMouse/assets/6781438/0673ace4-4be7-4a97-b1ac-6e38cef0b3bd)

If you have any screenshots to include with the listing, I gladly add them.

**Comment by VirtCode** [comment]
Wow, that's cool!
Yes, I probably should sign these builds properly, I just didn't have the time yet to read up on it. I'll let you know when I got around to doing that.
I'll probably also add some screenshots to the readme some time soon, so you could add those to the listing.

**Comment by IzzySoft** [comment]
> Wow, that's cool!

Glad you like it! Be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there e.g. from your Readme if you want to :smiley:

> I probably should sign these builds properly

When you start using the new "proper key", please attach a second APK signed with the current key to that first "new release" as well, for cross-checking and confirmation. For details, please see [How to keep your key safe and what measures to take for the event of loss?](https://f-droid.org/2023/09/03/reproducible-builds-signing-keys-and-binary-repos.html#lessons-learned-2-how-to-keep-your-key-safe-and-what-measures-to-take-for-the-event-of-loss)

> I'll probably also add some screenshots to the readme some time soon, so you could add those to the listing.

Great! Please give me a ping once they are there, so I can pick them up.
